dotnet/Models/Film.cs
namespace dotnet.Models
{
    public class Film
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }

        public int GenreId { get; set; }
        public Genre Genre { get; set; }
    }
}

dotnet/Controllers/FilmController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Web.Mvc;
using dotnet.Models;
using System.Linq;
using System;

namespace dotnet.Controllers
{
    public class FilmController : Controller
    {
        AppDBContext db = new AppDBContext();

        public ActionResult Index()
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            IEnumerable<Film> Films = db.Films.Include(g => g.Genre);

            return View(Films);
        }

        public ActionResult Create()
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            SelectList genres = new SelectList(db.Genres, "Id", "Name");
            ViewBag.Genres = genres;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Film film)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var film = db.Films
                .Include(f => f.Genre)
                .FirstOrDefault(f => f.Id == id);

            if (film == null)
            {
                return HttpNotFound();
            }

            return View(film);
        }

        public ActionResult Edit(int? id)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var Film = db.Films.Find(id);

            if (Film != null)
            {
                var genres = new SelectList(db.Genres, "Id", "Name", Film.GenreId);
                ViewBag.Genres = genres;
                return View(Film);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Film Film)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                db.Entry(Film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }

        public ActionResult Delete(int id)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var geme = db.Films.Find(id);
                db.Films.Remove(geme);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }
    }
}

dotnet/Views/Film/Create.cshtml
@{
    ViewBag.Title = "Create Film";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model dotnet.Models.Film

@using (Html.BeginForm())
{
    <div>
        @Html.LabelFor(m => m.Name, "Name")
        @Html.EditorFor(model => model.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.Description, "Description")
        @Html.TextAreaFor(model => model.Description)
    </div>
    <div>
        @Html.LabelFor(m => m.Link, "Link")
        @Html.EditorFor(model => model.Link)
    </div>
    <div>
        @Html.LabelFor(m => m.GenreId, "Genres")
        @Html.DropDownListFor(model => model.GenreId, ViewBag.Genres as SelectList)
    </div>
    <input type="submit" value="Create" />
}

dotnet/Views/Film/Details.cshtml
@model dotnet.Models.Film

@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="film-name">@Model.Name</h1>
<p class="film-genre">Genre: @Model.Genre.Name</p>
<p class="film-download"><a href="@Model.Link">Download</a></p>
<p class="film-description">@Model.Description</p>

dotnet/Views/Film/Edit.cshtml
@model dotnet.Models.Film

@{
    ViewBag.Title = "Edit film " + @Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "Film", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    <div>
        @Html.LabelFor(m => m.Name, "Name")
        @Html.EditorFor(m => m.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.Description, "Description")
        @Html.TextAreaFor(m => m.Description)
    </div>
    <div>
        @Html.LabelFor(m => m.Link, "Link")
        @Html.EditorFor(m => m.Link)
    </div>
    <div>
        @Html.LabelFor(m => m.GenreId, "Genres")
        @Html.DropDownListFor(model => model.GenreId, ViewBag.Genres as SelectList)
    </div>
    <input type="submit" value="Edit" />
}

dotnet/Views/Film/Index.cshtml
@model IEnumerable<dotnet.Models.Film>

@{
    ViewBag.Title = "Film list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Html.ActionLink("Create", "Create")</p><br />

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Genre</th>
        <th>Link</th>
        <th>Operations</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Description)</td>
            <td>@Html.DisplayFor(modelItem => item.Link)</td>
            <td>@Html.DisplayFor(modelItem => item.Genre.Name)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>