dotnet/Models/Genre.cs
namespace dotnet.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

dotnet/Controllers/GenreController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Web.Mvc;
using System;
using dotnet.Models;

namespace dotnet.Controllers
{
    public class GenreController : Controller
    {
        AppDBContext db = new AppDBContext();

        public ActionResult Index()
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            IEnumerable<Genre> genres = db.Genres;

            return View(genres);
        }

        public ActionResult Create()
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Create(Genre genre)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                db.Genres.Add(genre);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }

        public ActionResult Edit(int? id)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var genre = db.Genres.Find(id);

            if (genre == null)
            {
                return HttpNotFound();
            }

            return View(genre);
        }

        [HttpPost]
        public ActionResult Edit(Genre genre)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }

        public ActionResult Delete(int id)
        {
            if (Convert.ToInt32(Session["UserTypeId"]) != UserType.ADMIN)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var genre = db.Genres.Find(id);
                db.Genres.Remove(genre);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }
    }
}

dotnet/Views/Genre/Create.cshtml
@{
    ViewBag.Title = "Create Genre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model dotnet.Models.Genre

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name, "Name")
    @Html.EditorFor(model => model.Name)
    <input type="submit" value="Create" />
}

dotnet/Views/Genre/Edit.cshtml
@model dotnet.Models.Genre

@{
    ViewBag.Title = "Edit genre " + @Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "Genre", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    <div>
        @Html.LabelFor(m => m.Name, "Name")
        @Html.EditorFor(m => m.Name)
    </div>
    <input type="submit" value="Edit" />
}

dotnet/Views/Genre/Index.cshtml
@model IEnumerable<dotnet.Models.Genre>

@{
    ViewBag.Title = "Genre list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Html.ActionLink("Create", "Create")</p><br/>

<table>
    <tr>
        <th>Name</th>
        <th>Operations</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>